//******************** COMPONENTE PRINCIPAL *****************************************************


// CAMBIAR FILA SELECCIONADA GRID
export const CAMBIAR_VALOR_SELECCION_GRID = 'CAMBIAR_VALOR_SELECCION_GRID'
export const CAMBIAR_VALOR_SELECCION_GRID_EXITO = 'CAMBIAR_VALOR_SELECCION_GRID_EXITO'
export const CAMBIAR_VALOR_SELECCION_GRID_ERROR = 'CAMBIAR_VALOR_SELECCION_GRID_ERROR'

//ELIMINAR PROGRAMA
export const ELIMINAR_IMPROVEMENT_PROPOSALS = 'ELIMINAR_IMPROVEMENT_PROPOSALS'
export const ELIMINAR_IMPROVEMENT_PROPOSALS_EXITO = 'ELIMINAR_IMPROVEMENT_PROPOSALS_EXITO'
export const ELIMINAR_IMPROVEMENT_PROPOSALS_ERROR = 'ELIMINAR_IMPROVEMENT_PROPOSALS_ERROR'


//CONSULTA A API IMPROVEMENT_PROPOSALS PARA GRID
export const MOSTRAR_IMPROVEMENT_PROPOSALS = 'MOSTRAR_IMPROVEMENT_PROPOSALS'
export const MOSTRAR_IMPROVEMENT_PROPOSALS_EXITO = 'MOSTRAR_IMPROVEMENT_PROPOSALS_EXITO'
export const MOSTRAR_IMPROVEMENT_PROPOSALS_ERROR = 'MOSTRAR_IMPROVEMENT_PROPOSALS_ERROR'


//RESET STATE insertadoRiskManagement
export const CAMBIAR_STATE_INSERTADORISKMANAGEMENT = 'CAMBIAR_STATE_INSERTADORISKMANAGEMENT'
export const CAMBIAR_STATE_INSERTADORISKMANAGEMENT_EXITO = 'CAMBIAR_STATE_INSERTADORISKMANAGEMENT_EXITO'
export const CAMBIAR_STATE_INSERTADORISKMANAGEMENT_ERROR = 'CAMBIAR_STATE_INSERTADORISKMANAGEMENT_ERROR'

//CAMBIAR ESTADOS DINÁMICOS 
export const CAMBIAR_ESTADO_IMPROVEMENT_PROPOSALS = 'CAMBIAR_ESTADO_IMPROVEMENT_PROPOSALS'
export const CAMBIAR_ESTADO_IMPROVEMENT_PROPOSALS_EXITO = 'CAMBIAR_ESTADO_IMPROVEMENT_PROPOSALS_EXITO'
export const CAMBIAR_ESTADO_IMPROVEMENT_PROPOSALS_ERROR = 'CAMBIAR_ESTADO_IMPROVEMENT_PROPOSALS_ERROR'

//UPDATE IMPROVEMENT_PROPOSALS
export const UPDATE_IMPROVEMENT_PROPOSALS = 'UPDATE_IMPROVEMENT_PROPOSALS'
export const UPDATE_IMPROVEMENT_PROPOSALS_EXITO = 'UPDATE_IMPROVEMENT_PROPOSALS_EXITO'
export const UPDATE_IMPROVEMENT_PROPOSALS_ERROR = 'UPDATE_IMPROVEMENT_PROPOSALS_ERROR'


//******************** MODAL INSERTAR  *****************************************************

// CAMBIAR VISIBILIDAD
export const CAMBIAR_MODAL_VISIBILIDAD_INSERTAR = 'CAMBIAR_MODAL_VISIBILIDAD_INSERTAR'
export const CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_EXITO = 'CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_EXITO'
export const CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_ERROR = 'CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_ERROR'

//INSERTAR NUEVO RISK_MANAGER
export const INSERTAR_IMPROVEMENT_PROPOSALS_MODAL_INSERTAR = 'INSERTAR_IMPROVEMENT_PROPOSALS_MODAL_INSERTAR'
export const INSERTAR_IMPROVEMENT_PROPOSALS_MODAL_INSERTAR_EXITO = 'INSERTAR_IMPROVEMENT_PROPOSALS_MODAL_INSERTAR_EXITO'
export const INSERTAR_IMPROVEMENT_PROPOSALS_MODAL_INSERTAR_ERROR = 'INSERTAR_IMPROVEMENT_PROPOSALS_MODAL_INSERTAR_ERROR'
