//******************** COMPONENTE PRINCIPAL *****************************************************

export const CAMBIAR_VALOR_TAB_PEOPLE = 'CAMBIAR_VALOR_TAB_PEOPLE'
export const CAMBIAR_VALOR_TAB_PEOPLE_EXITO = 'CAMBIAR_VALOR_TAB_PEOPLE_EXITO'
export const CAMBIAR_VALOR_TAB_PEOPLE_ERROR = 'CAMBIAR_VALOR_TAB_PEOPLE_ERROR'

export const VER_MODAL_SOLICITAR_PERSONAL = 'VER_MODAL_SOLICITAR_PERSONAL'
export const VER_MODAL_SOLICITAR_PERSONAL_EXITO = 'VER_MODAL_SOLICITAR_PERSONAL_EXITO'
export const VER_MODAL_SOLICITAR_PERSONAL_ERROR = 'VER_MODAL_SOLICITAR_PERSONAL_ERROR'

export const GET_RESPONSABLES_MISION_ASOCIADA_SUB_MISION = 'GET_RESPONSABLES_MISION_ASOCIADA_SUB_MISION'
export const GET_RESPONSABLES_MISION_ASOCIADA_SUB_MISION_EXITO = 'GET_RESPONSABLES_MISION_ASOCIADA_SUB_MISION_EXITO'
export const GET_RESPONSABLES_MISION_ASOCIADA_SUB_MISION_ERROR = 'GET_RESPONSABLES_MISION_ASOCIADA_SUB_MISION_ERROR'

export const SET_MEMBER_SELECT_PEOPLE = 'SET_MEMBER_SELECT_PEOPLE'
export const SET_MEMBER_SELECT_PEOPLE_EXITO = 'SET_MEMBER_SELECT_PEOPLE_EXITO'
export const SET_MEMBER_SELECT_PEOPLE_ERROR = 'SET_MEMBER_SELECT_PEOPLE_ERROR'

export const GET_MY_MANAGER = 'GET_MY_MANAGER'
export const GET_MY_MANAGER_EXITO = 'GET_MY_MANAGER_EXITO'
export const GET_MY_MANAGER_ERROR = 'GET_MY_MANAGER_ERROR'

export const SET_SUB_MISION_ESTRUCTURA_SELECCIONADA = 'SET_SUB_MISION_ESTRUCTURA_SELECCIONADA'
export const SET_SUB_MISION_ESTRUCTURA_SELECCIONADA_EXITO = 'SET_SUB_MISION_ESTRUCTURA_SELECCIONADA_EXITO'
export const SET_SUB_MISION_ESTRUCTURA_SELECCIONADA_ERROR = 'SET_SUB_MISION_ESTRUCTURA_SELECCIONADA_ERROR'