export const MOSTRAR_LOG_PERSONA = 'MOSTRAR_LOG_PERSONA'
export const MOSTRAR_LOG_PERSONA_EXITO = 'MOSTRAR_LOG_PERSONA_EXITO'
export const MOSTRAR_LOG_PERSONA_ERROR = 'MOSTRAR_LOG_PERSONA_ERROR'

export const INSERTAR_NEW_LOG_PERSONA = 'INSERTAR_NEW_LOG_PERSONA'
export const INSERTAR_NEW_LOG_PERSONA_EXITO = 'INSERTAR_NEW_LOG_PERSONA_EXITO'
export const INSERTAR_NEW_LOG_PERSONA_ERROR = 'INSERTAR_NEW_LOG_PERSONA_ERROR'
