//UPDATE RISK_MANAGEMENT
export const MOSTRAR_CUSTOMER = 'MOSTRAR_CUSTOMER'
export const MOSTRAR_CUSTOMER_EXITO = 'MOSTRAR_CUSTOMER_EXITO'
export const MOSTRAR_CUSTOMER_ERROR = 'MOSTRAR_CUSTOMER_ERROR'

//OPEN DIALOGO NUEVO USUARIO
export const CAMBIAR_MODAL_NEW_CUSTOMER = 'CAMBIAR_MODAL_NEW_CUSTOMER'
export const CAMBIAR_MODAL_NEW_CUSTOMER_EXITO = 'CAMBIAR_MODAL_NEW_CUSTOMER_EXITO'
export const CAMBIAR_MODAL_NEW_CUSTOMER_ERROR = 'CAMBIAR_MODAL_NEW_CUSTOMER_ERROR'

//SESION CUSTOMER
export const CAMBIAR_VALOR_SELECCION_GRID_CUSTOMER = 'CAMBIAR_VALOR_SELECCION_GRID_CUSTOMER'
export const CAMBIAR_VALOR_SELECCION_GRID_CUSTOMER_EXITO = 'CAMBIAR_VALOR_SELECCION_GRID_CUSTOMER_EXITO'
export const CAMBIAR_VALOR_SELECCION_GRID_CUSTOMER_ERROR = 'CAMBIAR_VALOR_SELECCION_GRID_CUSTOMER_ERROR'

//UPDATE CUSTOMER
export const PUT_CUSTOMER = 'PUT_CUSTOMER'
export const PUT_CUSTOMER_EXITO = 'PUT_CUSTOMER_EXITO'
export const PUT_CUSTOMER_ERROR = 'PUT_CUSTOMER_ERROR'

//INSERTAR CUSTOMER
export const INSERTAR_NEW_CUSTOMER = 'INSERTAR_NEW_CUSTOMER'
export const INSERTAR_NEW_CUSTOMER_EXITO = 'INSERTAR_NEW_CUSTOMER_EXITO'
export const INSERTAR_NEW_CUSTOMER_ERROR = 'INSERTAR_NEW_CUSTOMER_ERROR'

export const CAMBIAR_MODAL_CUSTOMER_LOCATION = 'CAMBIAR_MODAL_CUSTOMER_LOCATION'
export const CAMBIAR_MODAL_CUSTOMER_LOCATION_EXITO = 'CAMBIAR_MODAL_CUSTOMER_LOCATION_EXITO'
export const CAMBIAR_MODAL_CUSTOMER_LOCATION_ERROR = 'CAMBIAR_MODAL_CUSTOMER_LOCATION_ERROR'

export const MOSTRAR_LOCATION_CUSTOMER = 'MOSTRAR_LOCATION_CUSTOMER'
export const MOSTRAR_LOCATION_CUSTOMER_EXITO = 'MOSTRAR_LOCATION_CUSTOMER_EXITO'
export const MOSTRAR_LOCATION_CUSTOMER_ERROR = 'MOSTRAR_LOCATION_CUSTOMER_ERROR'

export const CAMBIAR_MODAL_GESTION_CUSTOMER_LOCATION = 'CAMBIAR_MODAL_GESTION_CUSTOMER_LOCATION'
export const CAMBIAR_MODAL_GESTION_CUSTOMER_LOCATION_EXITO = 'CAMBIAR_MODAL_GESTION_CUSTOMER_LOCATION_EXITO'
export const CAMBIAR_MODAL_GESTION_CUSTOMER_LOCATION_ERROR = 'CAMBIAR_MODAL_GESTION_CUSTOMER_LOCATION_ERROR'

export const CAMBIAR_VALOR_SELECCION_GRID_LOCATION = 'CAMBIAR_VALOR_SELECCION_GRID_LOCATION'
export const CAMBIAR_VALOR_SELECCION_GRID_LOCATION_EXITO = 'CAMBIAR_VALOR_SELECCION_GRID_LOCATION_EXITO'
export const CAMBIAR_VALOR_SELECCION_GRID_LOCATION_ERROR = 'CAMBIAR_VALOR_SELECCION_GRID_LOCATION_ERROR'

export const INSERTAR_NEW_CUSTOMER_LOCATION = 'INSERTAR_NEW_CUSTOMER_LOCATION'
export const INSERTAR_NEW_CUSTOMER_LOCATION_EXITO = 'INSERTAR_NEW_CUSTOMER_LOCATION_EXITO'
export const INSERTAR_NEW_CUSTOMER_LOCATION_ERROR = 'INSERTAR_NEW_CUSTOMER_LOCATION_ERROR'

export const PUT_CUSTOMER_LOCATION = 'PUT_CUSTOMER_LOCATION'
export const PUT_CUSTOMER_LOCATION_EXITO = 'PUT_CUSTOMER_LOCATION_EXITO'
export const PUT_CUSTOMER_LOCATION_ERROR = 'PUT_CUSTOMER_LOCATION_ERROR'