//******************** COMPONENTE PRINCIPAL *****************************************************


// CAMBIAR FILA SELECCIONADA GRID
export const GET_USER_APP = 'GET_USER_APP'
export const GET_USER_APP_EXITO = 'GET_USER_APP_EXITO'
export const GET_USER_APP_ERROR = 'GET_USER_APP_ERROR'

export const VER_MODAL_ANADIR_APP_PERSONA = 'VER_MODAL_ANADIR_APP_PERSONA'
export const VER_MODAL_ANADIR_APP_PERSONA_EXITO = 'VER_MODAL_ANADIR_APP_PERSONA_EXITO'
export const VER_MODAL_ANADIR_APP_PERSONA_ERROR = 'VER_MODAL_ANADIR_APP_PERSONA_ERROR'

export const GET_ALL_APP = 'GET_ALL_APP'
export const GET_ALL_APP_EXITO = 'GET_ALL_APP_EXITO'
export const GET_ALL_APP_ERROR = 'GET_ALL_APP_ERROR'

export const POST_ASIGNAR_APP = 'POST_ASIGNAR_APP'
export const POST_ASIGNAR_APP_EXITO = 'POST_ASIGNAR_APP_EXITO'
export const POST_ASIGNAR_APP_ERROR = 'POST_ASIGNAR_APP_ERROR'

export const GET_RESULT_USERAPP_BY_TEAM = 'GET_RESULT_USERAPP_BY_TEAM'
export const GET_RESULT_USERAPP_BY_TEAM_EXITO = 'GET_RESULT_USERAPP_BY_TEAM_EXITO'
export const GET_RESULT_USERAPP_BY_TEAM_ERROR = 'GET_RESULT_USERAPP_BY_TEAM_ERROR'

export const VER_MODAL_VER_DETALLES_REQUERIMIENTOS = 'VER_MODAL_VER_DETALLES_REQUERIMIENTOS'
export const VER_MODAL_VER_DETALLES_REQUERIMIENTOS_EXITO = 'VER_MODAL_VER_DETALLES_REQUERIMIENTOS_EXITO'
export const VER_MODAL_VER_DETALLES_REQUERIMIENTOS_ERROR = 'VER_MODAL_VER_DETALLES_REQUERIMIENTOS_ERROR'

export const ITEM_SELECCIONADO_TEAM_REQUERIMENTS = 'ITEM_SELECCIONADO_TEAM_REQUERIMENTS'
export const ITEM_SELECCIONADO_TEAM_REQUERIMENTS_EXITO = 'ITEM_SELECCIONADO_TEAM_REQUERIMENTS_EXITO'
export const ITEM_SELECCIONADO_TEAM_REQUERIMENTS_ERROR = 'ITEM_SELECCIONADO_TEAM_REQUERIMENTS_ERROR'

export const DELETE_USER_APP = 'DELETE_USER_APP'
export const DELETE_USER_APP_EXITO = 'DELETE_USER_APP_EXITO'
export const DELETE_USER_APP_ERROR = 'DELETE_USER_APP_ERROR'