export const DESCARGAR_ADJUNTO_NOTIFICACION = 'DESCARGAR_ADJUNTO_NOTIFICACION'
export const DESCARGAR_ADJUNTO_NOTIFICACION_EXITO = 'DESCARGAR_ADJUNTO_NOTIFICACION_EXITO'
export const DESCARGAR_ADJUNTO_NOTIFICACION_ERROR = 'DESCARGAR_ADJUNTO_NOTIFICACION_ERROR'

export const POST_NUEVA_NOTIFICACION = 'POST_NUEVA_NOTIFICACION'
export const POST_NUEVA_NOTIFICACION_EXITO = 'POST_NUEVA_NOTIFICACION_EXITO'
export const POST_NUEVA_NOTIFICACION_ERROR = 'POST_NUEVA_NOTIFICACION_ERROR'

export const PUT_NOTIFICACION = 'PUT_NOTIFICACION'
export const PUT_NOTIFICACION_EXITO = 'PUT_NOTIFICACION_EXITO'
export const PUT_NOTIFICACION_ERROR = 'PUT_NOTIFICACION_ERROR'

export const GET_NOTIFICACION = 'GET_NOTIFICACION'
export const GET_NOTIFICACION_EXITO = 'GET_NOTIFICACION_EXITO'
export const GET_NOTIFICACION_ERROR = 'GET_NOTIFICACION_ERROR'
