//******************** COMPONENTE PRINCIPAL *****************************************************


// CAMBIAR FILA SELECCIONADA GRID
export const CAMBIAR_VALOR_SELECCION_GRID = 'CAMBIAR_VALOR_SELECCION_GRID'
export const CAMBIAR_VALOR_SELECCION_GRID_EXITO = 'CAMBIAR_VALOR_SELECCION_GRID_EXITO'
export const CAMBIAR_VALOR_SELECCION_GRID_ERROR = 'CAMBIAR_VALOR_SELECCION_GRID_ERROR'

//ELIMINAR PROGRAMA
export const ELIMINAR_RISK_MANAGEMENT = 'ELIMINAR_RISK_MANAGEMENT'
export const ELIMINAR_RISK_MANAGEMENT_EXITO = 'ELIMINAR_RISK_MANAGEMENT_EXITO'
export const ELIMINAR_RISK_MANAGEMENT_ERROR = 'ELIMINAR_RISK_MANAGEMENT_ERROR'


//CONSULTA A API RISK_MANAGEMENT PARA GRID
export const MOSTRAR_RISK_MANAGEMENT = 'MOSTRAR_RISK_MANAGEMENT'
export const MOSTRAR_RISK_MANAGEMENT_EXITO = 'MOSTRAR_RISK_MANAGEMENT_EXITO'
export const MOSTRAR_RISK_MANAGEMENT_ERROR = 'MOSTRAR_RISK_MANAGEMENT_ERROR'


//RESET STATE insertadoRiskManagement
export const CAMBIAR_STATE_INSERTADORISKMANAGEMENT = 'CAMBIAR_STATE_INSERTADORISKMANAGEMENT'
export const CAMBIAR_STATE_INSERTADORISKMANAGEMENT_EXITO = 'CAMBIAR_STATE_INSERTADORISKMANAGEMENT_EXITO'
export const CAMBIAR_STATE_INSERTADORISKMANAGEMENT_ERROR = 'CAMBIAR_STATE_INSERTADORISKMANAGEMENT_ERROR'

//CAMBIAR ESTADOS DINÁMICOS 
export const CAMBIAR_ESTADO_RISK_MANAGEMENT = 'CAMBIAR_ESTADO_RISK_MANAGEMENT'
export const CAMBIAR_ESTADO_RISK_MANAGEMENT_EXITO = 'CAMBIAR_ESTADO_RISK_MANAGEMENT_EXITO'
export const CAMBIAR_ESTADO_RISK_MANAGEMENT_ERROR = 'CAMBIAR_ESTADO_RISK_MANAGEMENT_ERROR'

//UPDATE RISK_MANAGEMENT
export const UPDATE_RISK_MANAGEMENT = 'UPDATE_RISK_MANAGEMENT'
export const UPDATE_RISK_MANAGEMENT_EXITO = 'UPDATE_RISK_MANAGEMENT_EXITO'
export const UPDATE_RISK_MANAGEMENT_ERROR = 'UPDATE_RISK_MANAGEMENT_ERROR'


//******************** MODAL INSERTAR  *****************************************************

// CAMBIAR VISIBILIDAD
export const CAMBIAR_MODAL_VISIBILIDAD_INSERTAR = 'CAMBIAR_MODAL_VISIBILIDAD_INSERTAR'
export const CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_EXITO = 'CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_EXITO'
export const CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_ERROR = 'CAMBIAR_MODAL_VISIBILIDAD_INSERTAR_ERROR'

//INSERTAR NUEVO RISK_MANAGER
export const INSERTAR_RISK_MANAGEMENT_MODAL_INSERTAR = 'INSERTAR_RISK_MANAGEMENT_MODAL_INSERTAR'
export const INSERTAR_RISK_MANAGEMENT_MODAL_INSERTAR_EXITO = 'INSERTAR_RISK_MANAGEMENT_MODAL_INSERTAR_EXITO'
export const INSERTAR_RISK_MANAGEMENT_MODAL_INSERTAR_ERROR = 'INSERTAR_RISK_MANAGEMENT_MODAL_INSERTAR_ERROR'
