//***********  CAMBIAR ESTADO REDUX *********/

export const CAMBIAR_ESTADO = 'CAMBIAR_ESTADO'
export const CAMBIAR_ESTADO_EXITO = 'CAMBIAR_ESTADO_EXITO'
export const CAMBIAR_ESTADO_ERROR = 'CAMBIAR_ESTADO_ERROR'


//***********  PETICIONES A API *********/

export const MOSTRAR_API = 'MOSTRAR_API'
export const MOSTRAR_API_EXITO = 'MOSTRAR_API_EXITO'
export const MOSTRAR_API_ERROR = 'MOSTRAR_API_ERROR'

export const INSERTAR_API = 'INSERTAR_API'
export const INSERTAR_API_EXITO = 'INSERTAR_API_EXITO'
export const INSERTAR_API_ERROR = 'INSERTAR_API_ERROR'

export const UPDATE_API = 'UPDATE_API'
export const UPDATE_API_EXITO = 'UPDATE_API_EXITO'
export const UPDATE_API_ERROR = 'UPDATE_API_ERROR'


