#!/bin/sh

# Comprobamos si existe la base de datos
if pipenv run python manage.py showmigrations tm | grep -q '0001_initial'; then
	echo '* Ya existe la base de datos, con la primera migración realizada'

	echo '------ Actualizamos migraciones Django ------'
	# Actualizamos migraciones de la base de datos de TM
	pipenv run python manage.py makemigrationstm

	# Aplicamos las migraciones a la base de datos de TM
	pipenv run python manage.py migratetm

	# Aplicamos las migraciones de Django
	pipenv run python manage.py migrate

else

	#echo '------ Eliminamos directorio tm/migrations ------'
	# Borramos el directorio migrations
	#rm -R ./tm/migrations

	echo '------ Creamos migraciones Django ------'
	# Creamos migraciones de la base de datos de TM
	pipenv run python manage.py makemigrationstm

	# Aplicamos las migraciones a la base de datos de TM
	pipenv run python manage.py migratetm

	# Aplicamos las migraciones de Django
	pipenv run python manage.py migrate

	# Creamos los usuarios administradores 
	pipenv run python manage.py loaddata ./tm/seeds/31-05-22_create_user.json
fi

echo '------ Levantamos el servidor Django ------'
pipenv run python manage.py runserver 0.0.0.0:8000
